services:
    app:
        build:
            context: ./docker/php
        container_name: charlie_app
        working_dir: /var/www/html
        environment:
            DB_HOST: db
            DB_PORT: 3306
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: charlie_web
        ports:
            - "8098:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: charlie_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: charlie
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravelpassword
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3309:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    mailpit:
        image: axllent/mailpit:latest
        container_name: mailpit
        ports:
            - "1025:1025" # SMTP
            - "8025:8025" # Web UI
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
